### ISSUE TITLE
(short issue description)

### ISSUE THREAD

**Issue by claviola** [ulises-jeremias/dotfiles#36]
### Describe the bug

Install doesn't work without LastPass

### Expected Behavior

Automated deployment of the dotfiles/a mention of the dependency in the docs

### Current Behavior

```
🔃 Running '/home/claviola/.dotfiles/install.sh'
Installing chezmoi to '/home/claviola/.local/bin/chezmoi'
info found version 2.46.0 for latest/linux/amd64
info installed /home/claviola/.local/bin/chezmoi
Running 'chezmoi init --apply --source=/home/claviola/.dotfiles'
chezmoi: template: dot_config/private_credentials/private_github_access_token_notifications.tmpl:1:11: executing "dot_config/private_credentials/private_github_access_token_notifications.tmpl" at <lastpassRaw "github_access_token_notifications">: error calling lastpassRaw: exec: "lpass": executable file not found in $PATH
```

If I install the `lastpass-cli` package so that `lpass` exists:

```
Running 'chezmoi init --apply --source=/home/claviola/.dotfiles'
Error: Could not find decryption key. Perhaps you need to login with `lpass login`.
```

So it seems like this is a hard dependency.

### Reproduction Steps

Run the script on https://github.com/ulises-jeremias/dotfiles?tab=readme-ov-file#getting-started- on a (relatively) pristine Debian VM

### Possible Solution

Make LastPass optional

### Version used

8f6c5768ca20471e01e602555fc32f5b13499a0b

### Environment details (OS name and version, etc.)

Debian 12.4 (bookworm)

**Comment by ulises-jeremias** [comment]
@claviola thanks for opening this issue! will do some changes asap to make lastpass an optional dependency

**Comment by ulises-jeremias** [comment]
@claviola I just fixed this issue. I made it to only use lastpass when the variable `personal` is set. You can check this commit for reference!

https://github.com/ulises-jeremias/dotfiles/commit/d1f84bc1f6f586a8f631356a93a96c4e4c36c281
